### ISSUE TITLE
'Figure' object has no attribute 'add_vline'

### ISSUE THREAD

**Issue by inesbsilveira** [SMByC/CCD-Plugin#10]
Traceback (most recent call last):
  File "/Users/inesinghambs/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CCD_Plugin/utils/system_utils.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/Users/inesinghambs/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CCD_Plugin/utils/system_utils.py", line 91, in wrapper
    obj_returned = func(*args, **kwargs)
  File "/Users/inesinghambs/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CCD_Plugin/gui/CCD_Plugin_dockwidget.py", line 170, in new_plot
    self.html_file = generate_plot(ccdc_result_info, timeseries, date_range, dataset, band_or_index, CCD_Plugin.tmp_dir)
  File "/Users/inesinghambs/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CCD_Plugin/core/plot.py", line 120, in generate_plot
    fig.add_vline(x=break_date, line_width=1, line_dash="dash", line_color="red",
AttributeError: 'Figure' object has no attribute 'add_vline'

**Comment by XavierCLL** [comment]
Hi @inesbsilveira 

Are you using the latest version of the plugin? v23.11? if so, it seems that an old version of Plotty library is loading, maybe because you had installed an old version of this plugin before, then:

* Remove this directory: /Users/inesinghambs/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CCD_Plugin
* Restart Qgis and reinstall the plugin

Let me know if that fixes the issue.

**Comment by XavierCLL** [comment]
Closing this due to inactivity, open it again if you have more feedback, thanks.
