### ISSUE TITLE
'Figure' object has no attribute 'add_vline'

### ISSUE THREAD

**Issue by jelevet** [SMByC/CCD-Plugin#12]
Hello !
Great plugin ! unfortunately I had this issue : 

Traceback (most recent call last):
  File "/Users/jerome/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CCD_Plugin/utils/system_utils.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/Users/jerome/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CCD_Plugin/utils/system_utils.py", line 91, in wrapper
    obj_returned = func(*args, **kwargs)
  File "/Users/jerome/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CCD_Plugin/gui/CCD_Plugin_dockwidget.py", line 170, in new_plot
    self.html_file = generate_plot(ccdc_result_info, timeseries, date_range, dataset, band_or_index, CCD_Plugin.tmp_dir)
  File "/Users/jerome/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/CCD_Plugin/core/plot.py", line 120, in generate_plot
    fig.add_vline(x=break_date, line_width=1, line_dash="dash", line_color="red",
AttributeError: 'Figure' object has no attribute 'add_vline'

Thanks !

**Comment by XavierCLL** [comment]
Hi @jelevet 

It seems that you have an old version of Plotly lib in your system, maybe provided by another plugin. Please open the python console (Plugins > Python Console) and copy-paste here what returns these commands:

```python
import plotly
plotly.__version__
plotly.__file__
```

**Comment by XavierCLL** [comment]
Try to use the latest version, closing due to inactivity
